version: "3.7"

services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - keep-secrets
networks:
  keep-secrets:
    name: keep-secrets
    external: true
volumes:
  redis_data:
    driver: local